// Generated by the admin-dashboard onboarding flow. Do not edit by hand —
// re-run "Add feedback button" in the dashboard to rotate the token.
export const DASHBOARD_FEEDBACK = {
  ingestUrl: "https://feedback.diyhelper.org/api/ingest/feedback",
  ingestToken: "diyhelper2.efe38c99fd459c341ca089db6a4beed577f9cf32bfa7fa52",
};